DoAnTotNghiep/Controllers/UserAppointmentController.cs
using DoAnTotNghiep.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
namespace DoAnTotNghiep.Controllers
{
    public class UserAppointmentController : Controller
    {
        QlphongKhamNhaKhoaContext db = new QlphongKhamNhaKhoaContext();

        [Route("userappointmentlist")]
        [HttpGet]
        public IActionResult UserAppointmentList(int? page, string statusFilter)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;

            var username = HttpContext.Session.GetString("Username");
            var user = db.Users.FirstOrDefault(u => u.Username == username);
            if (user == null)
            {
                ViewBag.NoDataMessage = "No appointments found for the current user.";
                return View();
            }

            var userid = user.UserId;

            IQueryable<Appointment> appointments = db.Appointments
                .Include(a => a.Doctor)
                .Include(a => a.User)
                .Where(a => a.UserId == userid);

            if (!string.IsNullOrEmpty(statusFilter))
            {
                int status = int.Parse(statusFilter);
                appointments = appointments.Where(a => a.Status == status);
                ViewBag.SelectedStatus = statusFilter;
            }

            var pagedAppointments = appointments.ToPagedList(pageNumber, pageSize);

            return View(pagedAppointments);
        }

        [Route("userappointmentdetail")]
        [HttpGet]
        public IActionResult UserAppointmentDetail(string id)
        {
            var appointment = db.Appointments
                .Include(a => a.Doctor)
                .Include(a => a.Service)
                .FirstOrDefault(a => a.AppointmentId == id);
            if(appointment == null)
            {
                return NotFound();
            }

            var user = db.Users.Find(appointment.UserId);
            ViewBag.UserName = user.Name;
            ViewBag.UserPhone = user.PhoneNumber;
            ViewBag.UserEmail = user.Email;

            return View(appointment);
        }

        [Route("edituserappointment")]
        [HttpGet]
        public IActionResult EditUserAppointment(string id)
        {
            var appointment = db.Appointments.Include(a => a.Doctor)
                .Include(a => a.Service)
                .Include(a => a.User)
                .FirstOrDefault(a => a.AppointmentId == id);

            if(appointment == null)
            {
                return NotFound();
            }

            ViewBag.UserName = appointment.User?.Name;
            ViewBag.UserPhone = appointment.User?.PhoneNumber;
            ViewBag.UserEmail = appointment.User?.Email;

            ViewBag.ServiceId = new SelectList(db.Services.ToList(), "ServiceId", "ServiceName", appointment.ServiceId);
            ViewBag.DoctorId = new SelectList(db.Doctors.ToList(), "DoctorId", "Name", appointment.DoctorId);

            return View(appointment);
        }

        [Route("edituserappointment")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditUserAppointment(Appointment appointment)
        {
            // Kiểm tra xem đối tượng đã tồn tại trong cơ sở dữ liệu chưa
            var existingAppointment = db.Appointments.Find(appointment.AppointmentId);

            // Nếu không tìm thấy, trả về NotFound
            if (existingAppointment == null)
            {
                return NotFound();
            }

            // Cập nhật các thuộc tính của đối tượng đã tồn tại từ đối tượng mới
            existingAppointment.ServiceId = appointment.ServiceId;
            existingAppointment.DoctorId = appointment.DoctorId;

            // Lưu thay đổi vào cơ sở dữ liệu
            db.SaveChanges();

            // Cập nhật TempData
            TempData["SuccessMessage"] = "Appointment edited successfully";

            // Chuyển hướng đến action khác, ví dụ: UserAppointmentList
            return RedirectToAction("UserAppointmentList");
        }

        [Route("cancelappointment")]
        [HttpGet]
        public IActionResult CancelAppointment(string id)
        {
            var appointment = db.Appointments.FirstOrDefault(d => d.AppointmentId == id);
            db.Appointments.Remove(appointment);
            db.SaveChanges();
            TempData["SuccessMessage"] = "Appointment canceled successfully";

            return RedirectToAction("UserAppointmentList");
        }
    }
}

DoAnTotNghiep/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="../Dentist/img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="colorlib">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Dentist</title>

	<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
	<!--
	CSS
	============================================= -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>

	<link rel="stylesheet" href="../Dentist/css/linearicons.css">
	<link rel="stylesheet" href="../Dentist/css/font-awesome.min.css">
	<link rel="stylesheet" href="../Dentist/css/bootstrap.css">
	<link rel="stylesheet" href="../Dentist/css/magnific-popup.css">
	<link rel="stylesheet" href="../Dentist/css/nice-select.css">
	<link rel="stylesheet" href="../Dentist/css/animate.min.css">
	<link rel="stylesheet" href="../Dentist/css/jquery-ui.css">
	<link rel="stylesheet" href="../Dentist/css/owl.carousel.css">
	<link rel="stylesheet" href="../Dentist/css/main.css">
	<link rel="stylesheet" href="../../Admin/assets/vendors/mdi/css/materialdesignicons.min.css">
	<link rel="stylesheet" href="../../Admin/assets/vendors/css/vendor.bundle.base.css">
	<!-- endinject -->
	<!-- Plugin css for this page -->
	<!-- End plugin css for this page -->
	<!-- inject:css -->
	<!-- endinject -->
	<!-- Layout styles -->
	<link rel="stylesheet" href="../../Admin/assets/css/style.css">
	<!-- End layout styles -->
	<link rel="shortcut icon" href="../../Admin/assets/images/favicon.ico" />
	<link rel="icon" href="../../Invoice/img/core-img/favicon.ico">

	<!-- Core Stylesheet -->
	<link rel="stylesheet" href="../../Invoice/css/style.css">
</head>
<body>
	<header id="header" id="home">
		<div class="header-top">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6 col-sm-6 col-4 header-top-left no-padding">
						<a href="index.html"><img src="../Dentist/img/logo.png" alt="" title="" /></a>
					</div>
					<div class="col-lg-6 col-sm-6 col-8 header-top-right no-padding">
						<a class="btns" href="tel:+953 012 3654 896">+953 012 3654 896</a>
						<a class="btns" href="mailto:support@colorlib.com">support@colorlib.com</a>
						<a class="icons" href="tel:+953 012 3654 896">
							<span class="lnr lnr-phone-handset"></span>
						</a>
						<a class="icons" href="mailto:support@colorlib.com">
							<span class="lnr lnr-envelope"></span>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="container main-menu">
			<div class="row align-items-center justify-content-between d-flex">
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li class="menu-active"><a asp-controller="Home" asp-action="Index">Home</a></li>
						<li><a href="about.html">About</a></li>
						<li><a asp-controller="Home" asp-action="ServiceList">Services</a></li>
						<li><a href="opening-hour.html">Opening Hour </a></li>
						<li class="menu-has-children">
							<a href="">Blog</a>
							<ul>
								<li><a href="blog-home.html">Blog Home</a></li>
								<li><a href="blog-single.html">Blog Single</a></li>
								<li class="menu-has-children">
									<a href="">Level 2</a>
									<ul>
										<li><a href="#">Item One</a></li>
										<li><a href="#">Item Two</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a asp-controller="UserAppointment" asp-action="UserAppointmentList">Appointment List</a></li>
						<li><a asp-controller="Home" asp-action="NewAppointment">Appointment</a></li>
						<li><a asp-controller="Home" asp-action="Profile">Profile</a></li>
						<li><a asp-controller="UserLogin" asp-action="Logout">Log out</a></li>
						@* <li>@username</li> *@
					</ul>
				</nav><!-- #nav-menu-container -->
				<div class="menu-social-icons">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-behance"></i></a>
				</div>
			</div>
		</div>
	</header><!-- #header -->
	@RenderBody()

	<!-- start footer Area -->
	<footer class="footer-area section-gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-2  col-md-6">
					<div class="single-footer-widget">
						<h6>Top Products</h6>
						<ul class="footer-nav">
							<li><a href="#">Managed Website</a></li>
							<li><a href="#">Manage Reputation</a></li>
							<li><a href="#">Power Tools</a></li>
							<li><a href="#">Marketing Service</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4  col-md-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">Contact Us</h6>
						<p>
							56/8, bir uttam qazi nuruzzaman road, west panthapath, kalabagan, Dhanmondi, Dhaka - 1205
						</p>
						<h3>012-6532-568-9746</h3>
						<h3>012-6532-568-97468</h3>
					</div>
				</div>
				<div class="col-lg-6  col-md-12">
					<div class="single-footer-widget newsletter">
						<h6>Newsletter</h6>
						<p>You can trust us. we only send promo offers, not a single spam.</p>
						<div id="mc_embed_signup">
							<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

								<div class="form-group row" style="width: 100%">
									<div class="col-lg-8 col-md-12">
										<input name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '" required="" type="email">
										<div style="position: absolute; left: -5000px;">
											<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
										</div>
									</div>

									<div class="col-lg-4 col-md-12">
										<button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
									</div>
								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="row footer-bottom d-flex justify-content-between">
				<p class="col-lg-8 col-sm-12 footer-text m-0">
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</p>
				<div class="col-lg-4 col-sm-12 footer-social">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-behance"></i></a>
				</div>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->

	<script src="../Dentist/js/vendor/jquery-2.2.4.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.../Dentist/js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="../Dentist/js/vendor/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
	<script src="../Dentist/js/easing.min.js"></script>
	<script src="../Dentist/js/hoverIntent.js"></script>
	<script src="../Dentist/js/superfish.min.js"></script>
	<script src="../Dentist/js/jquery.ajaxchimp.min.js"></script>
	<script src="../Dentist/js/jquery.magnific-popup.min.js"></script>
	<script src="../Dentist/js/jquery-ui.js"></script>
	<script src="../Dentist/js/owl.carousel.min.js"></script>
	<script src="../Dentist/js/jquery.nice-select.min.js"></script>
	<script src="../Dentist/js/mail-script.js"></script>
	<script src="../Dentist/js/main.js"></script>
	@* <script src="../../Admin/assets/vendors/js/vendor.bundle.base.js"></script>
	<!-- endinject -->
	<!-- Plugin js for this page -->
	<!-- End plugin js for this page -->
	<!-- inject:js -->
	<script src="../../Invoice/js/jquery/jquery-2.2.4.min.js"></script>
	<!-- Popper js -->
	<script src="../../Invoice/js/bootstrap/popper.min.js"></script>
	<!-- Bootstrap js -->
	<script src="../../Invoice/js/bootstrap/bootstrap.min.js"></script>
	<!-- All Plugins js -->
	<script src="../../Invoice/js/plugins/plugins.js"></script>
	<!-- Active js -->
	<script src="../../Invoice/js/active.js"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="../../Admin/assets/js/off-canvas.js"></script>
	<script src="../../Admin/assets/js/hoverable-collapse.js"></script>
	<script src="../../Admin/assets/js/misc.js"></script> *@
	@RenderSection("Scripts", required: false)
</body>
</html>